package code

var zhCNText = map[int]string{
	ServerError:             "内部服务器错误",
	TooManyRequests:         "请求过多",
	ParamBindError:          "参数信息错误",
	AuthorizationError:      "签名信息错误",
	DictionarySubItemError:  "字典子项获取失败",
	FeedbackCreateError:     "提交反馈信息失败",
	FeedbackListError:       "获取用户反馈记录失败",
	RecruitInfoDetailError:  "获取校招详情失败",
	FollowCompanyError:      "关注公司操作失败",
	RecruitInfoListError:    "获取校招信息列表失败",
	SalaryInfoDetailError:   "薪资详情信息获取失败",
	SalaryVoteError:         "薪资可信度投票失败",
	SalaryInfoCreateError:   "薪资爆料信息提交失败",
	SalaryInfoListError:     "薪资爆料数据获取失败",
	DeletePostByUserError:   "删除数据异常",
	PostInfoDetailError:     "获取帖子详情失败",
	EditPostInfoError:       "编辑发布内容失败",
	GetCommentListError:     "获取评论信息失败",
	GetPostEditDetailError:  "获取编辑内容失败",
	GetPostIdsListError:     "获取帖子数据失败",
	LikePostError:           "点赞失败",
	GetPostListByIdsError:   "获取帖子数据失败",
	PostListBySearchError:   "搜索帖子数据获取失败",
	PagePostListByUserError: "获取用户发布数据失败",
	PagePostStarListError:   "获取用户收藏数据失败",
	CreatePostCommentError:  "评论数据提交失败",
	StarPostError:           "收藏帖子操作失败",
	FollowUserError:         "关注用户操作失败",
	BaseUserInfoError:       "获取用户基础信息失败",
	UpdateUserBaseInfoError: "更新用户基础信息失败",
	WXLoginError:            "获取微信授权失败",
	FocusSelfError:          "无法关注自己哦",
}
