///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package like_info

import (
	"fmt"
	"time"

	"campus-recruiting-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *LikeInfo {
	return new(LikeInfo)
}

func NewQueryBuilder() *likeInfoQueryBuilder {
	return new(likeInfoQueryBuilder)
}

func (t *LikeInfo) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type likeInfoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *likeInfoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *likeInfoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&LikeInfo{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *likeInfoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&LikeInfo{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *likeInfoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&LikeInfo{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *likeInfoQueryBuilder) First(db *gorm.DB) (*LikeInfo, error) {
	ret := &LikeInfo{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *likeInfoQueryBuilder) QueryOne(db *gorm.DB) (*LikeInfo, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *likeInfoQueryBuilder) QueryAll(db *gorm.DB) ([]*LikeInfo, error) {
	var ret []*LikeInfo
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *likeInfoQueryBuilder) Limit(limit int) *likeInfoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *likeInfoQueryBuilder) Offset(offset int) *likeInfoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *likeInfoQueryBuilder) WhereId(p mysql.Predicate, value int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereIdIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereIdNotIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) OrderById(asc bool) *likeInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *likeInfoQueryBuilder) WhereCreatedAt(p mysql.Predicate, value time.Time) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereCreatedAtIn(value []time.Time) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) OrderByCreatedAt(asc bool) *likeInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *likeInfoQueryBuilder) WhereUpdatedAt(p mysql.Predicate, value time.Time) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) OrderByUpdatedAt(asc bool) *likeInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *likeInfoQueryBuilder) WhereTopicId(p mysql.Predicate, value int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "topic_id", p),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereTopicIdIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "topic_id", "IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereTopicIdNotIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "topic_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) OrderByTopicId(asc bool) *likeInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "topic_id "+order)
	return qb
}

func (qb *likeInfoQueryBuilder) WhereType(p mysql.Predicate, value int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", p),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereTypeIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereTypeNotIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) OrderByType(asc bool) *likeInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "type "+order)
	return qb
}

func (qb *likeInfoQueryBuilder) WhereFromUid(p mysql.Predicate, value int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "from_uid", p),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereFromUidIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "from_uid", "IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereFromUidNotIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "from_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) OrderByFromUid(asc bool) *likeInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "from_uid "+order)
	return qb
}

func (qb *likeInfoQueryBuilder) WhereState(p mysql.Predicate, value int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "state", p),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereStateIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "state", "IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) WhereStateNotIn(value []int32) *likeInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "state", "NOT IN"),
		value,
	})
	return qb
}

func (qb *likeInfoQueryBuilder) OrderByState(asc bool) *likeInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "state "+order)
	return qb
}
