[system]
    name = "campus-recruiting"
    mode = "dev"
    port = 8080
    version = "v0.0.1"
    start_time = "2022-12-12"
    machine_id = 1

[hashids]
    length = 12
    secret = "6ab6122836cfef95f8db"

[language]
    local = "zh-cn"

[mail]
    host = "smtp.163.com"
    pass = ""
    port = 465
    to = ""
    user = ""

[mysql]

    [mysql.base]
        connmaxlifetime = 60
        maxidleconn = 60
        maxopenconn = 10

    [mysql.read]
        addr = "127.0.0.1:3306"
        name = "campus-recruiting"
        pass = "123456"
        user = "root"

    [mysql.write]
        addr = "127.0.0.1:3306"
        name = "campus-recruiting"
        pass = "123456"
        user = "root"

[redis]
    addr = "127.0.0.1:6379"
    db = "0"
    maxretries = 3
    minidleconns = 5
    pass = ""
    poolsize = 10

[log]
    level = "debug"
    filename = "campus-recruiting-api.log"
    maxsize = 200
    max_age = 30
    max_backups = 7

[wxapplets]
    app_id = "xxx"
    app_secret = "xxx"