///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package star_info

import (
	"fmt"
	"time"

	"campus-recruiting-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *StarInfo {
	return new(StarInfo)
}

func NewQueryBuilder() *starInfoQueryBuilder {
	return new(starInfoQueryBuilder)
}

func (t *StarInfo) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type starInfoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *starInfoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *starInfoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&StarInfo{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *starInfoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&StarInfo{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *starInfoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&StarInfo{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *starInfoQueryBuilder) First(db *gorm.DB) (*StarInfo, error) {
	ret := &StarInfo{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *starInfoQueryBuilder) QueryOne(db *gorm.DB) (*StarInfo, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *starInfoQueryBuilder) QueryAll(db *gorm.DB) ([]*StarInfo, error) {
	var ret []*StarInfo
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *starInfoQueryBuilder) Limit(limit int) *starInfoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *starInfoQueryBuilder) Offset(offset int) *starInfoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *starInfoQueryBuilder) WhereId(p mysql.Predicate, value int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereIdIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereIdNotIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) OrderById(asc bool) *starInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *starInfoQueryBuilder) WhereCreatedAt(p mysql.Predicate, value time.Time) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereCreatedAtIn(value []time.Time) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) OrderByCreatedAt(asc bool) *starInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *starInfoQueryBuilder) WhereUpdatedAt(p mysql.Predicate, value time.Time) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) OrderByUpdatedAt(asc bool) *starInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *starInfoQueryBuilder) WhereFromUid(p mysql.Predicate, value int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "from_uid", p),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereFromUidIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "from_uid", "IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereFromUidNotIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "from_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) OrderByFromUid(asc bool) *starInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "from_uid "+order)
	return qb
}

func (qb *starInfoQueryBuilder) WhereType(p mysql.Predicate, value int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", p),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereTypeIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereTypeNotIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) OrderByType(asc bool) *starInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "type "+order)
	return qb
}

func (qb *starInfoQueryBuilder) WhereTopicId(p mysql.Predicate, value int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "topic_id", p),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereTopicIdIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "topic_id", "IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) WhereTopicIdNotIn(value []int32) *starInfoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "topic_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *starInfoQueryBuilder) OrderByTopicId(asc bool) *starInfoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "topic_id "+order)
	return qb
}
